script/deploy: better feedback for directory tests
If a directory fails a test, report which one failed.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -79,11 +79,11 @@ fi
 if [ -n "$CHECK" ]; then
   echo "Processing command: check"
   echo "  checking: directories exist and are writable"
-  ssh $SERVER "sh -c 'test -d $DEPLOY && \
-                      test -d $DEPLOY/shared && \
-                      test -d $DEPLOY/releases && \
-                      test -w $DEPLOY && \
-                      test -w $DEPLOY/releases'"
+  ssh $SERVER "sh -c '(test -d $DEPLOY          || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
+                      (test -d $DEPLOY/shared   || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
+                      (test -d $DEPLOY/releases || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
+                      (test -w $DEPLOY          || (echo \"  failed -w: $DEPLOY\" && exit 1)) && \
+                      (test -w $DEPLOY/releases || (echo \"  failed -w: $DEPLOY\" && exit 1))'"
   echo "  checking: executables exist"
   ssh $SERVER "sh -c 'which gem git > /dev/null'"
   echo "  checking: gem versions"
