script/deploy: check that JavaScript is minimized during "check" target
Just in case the developer forgets to run "rake js:minify:create", do an
automated check during the "check" target.

Note that we use LOCAL_REF and REMOTE_REF temporary variables here to
keep things clear and not clobber the value of the REF variable set
during command line argument processing.

Due to apparent bugs in Google's Closure compiler (the command-line
version, at least), we are still using the Yahoo compressor and the
Closure support is commented out.

Another issue still to be resolved is how to actually bail in the event
of an error seeing as our "exit 1" commands don't actually abort the
shell script in the event that minimization wasn't performed correctly
(because the exit status applies to the subshell delimited by the
parentheses, and doesn't "bubble up" and terminate the actual shell
script.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -203,6 +203,24 @@ fi
 
 if [ -n "$DO_CHECK" ]; then
   echo "Processing command: check"
+  echo "  checking: JavaScript is correctly minimized"
+  #COMPRESSOR=/usr/local/bin/closure/compiler.jar
+  COMPRESSOR=/usr/local/bin/yuicompressor.jar
+  test -f $COMPRESSOR || (echo "  failed: compressor not found at $COMPRESSOR" && exit 1)
+  #test -r $COMPRESSOR || (echo "  failed: compressor not readable at $COMPRESSOR" && exit 1)
+  TMPDIR=$(mktemp -q -d /private/tmp/deploy.XXXXXX) || (echo "  failed: could not create temporary directory" && exit 1)
+  if [ -z "$REF" ]; then
+    LOCAL_REF=$BRANCH
+  else
+    LOCAL_REF=$REF
+  fi
+  for JS in $(ls public/javascripts/*.max.js); do
+    git show $LOCAL_REF:$JS > $TMPDIR/max.js
+    git show $LOCAL_REF:${JS/.max.js/.min.js} > $TMPDIR/min.js
+    java -jar $COMPRESSOR -o $TMPDIR/out.js $TMPDIR/max.js
+    #java -jar $COMPRESSOR --js=$TMPDIR/max.js --js_output_file=$TMPDIR/out.js
+    diff -q $TMPDIR/min.js $TMPDIR/out.js > /dev/null || (echo "  failed: $JS is not minimized in $LOCAL_REF" && exit 1)
+  done
   echo "  checking: directories exist and are writable"
   ssh $SERVER "sh -c '(test -d $DEPLOY          || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
                       (test -d $DEPLOY/shared   || (echo \"  failed -d: $DEPLOY/shared\" && exit 1)) && \
@@ -233,12 +251,14 @@ if [ -n "$DO_DEPLOY" ]; then
   SHARED=$DEPLOY/shared
   CHECKOUT=$DEPLOY/releases/$TIMESTAMP
   if [ -z "$REF" ]; then
-    REF=origin/$BRANCH
+    REMOTE_REF=origin/$BRANCH
+  else
+    REMOTE_REF=$REF
   fi
   ssh $SERVER "sh -c '(test ! -e $TIMESTAMP || (echo \"  failed: $CHECKOUT already exists\" && exit 1)) && \
                       git clone --shared $REPO $CHECKOUT && \
                       cd $CHECKOUT && \
-                      git checkout -b deploy $REF && \
+                      git checkout -b deploy $REMOTE_REF && \
                       (echo $TIMESTAMP > $CHECKOUT/REVISION) && \
                       rm -rf $CHECKOUT/log \
                              $CHECKOUT/public/system \
