script/deploy: add "help" subcommand and switches
Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -39,17 +39,19 @@ usage() {
   echo "Options:"
   echo "     --staging    deploy to staging environment"
   echo "     --rev=REF    deploy specified tag/branch/commit"
+  exit
 }
 
 #
 # main
 #
 
-trap 'test -n "$SUCCESS" || echo "error: aborted"' EXIT
-
 # process arguments
 while test $# != 0; do
   case "$1" in
+    -h|--help|help)
+      usage
+      ;;
     --staging|staging|--stage|stage)
       staging_environment_overrides
       ;;
@@ -106,6 +108,8 @@ while test $# != 0; do
   esac
   shift
 done
+
+trap 'test -n "$SUCCESS" || echo "error: aborted"' EXIT
 
 echo "Environment for this session: $ENVIRONMENT"
 
