script/deploy: big refactor using `run` function
Taking advantage of the fact that we have `ControlMaster` and
`ControlPersist` settings in our `~/.ssh/config`, we can get rid of the
very long strings of "&&"-ed remote commands and instead fire off
separate `ssh` commands for each task, with no real overhead.

This commit adds a `run` helper function to abstract this pattern away,
and give us some niceties for "free", such as a log/deploy.log file.

It is almost certainly not what a Bash veteran would have written, but
it works, and the script is arguably more readable now.

The next big fish to fry here will be involving a local mirror repo for
the initial clone, which should speed up things considerably.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -1,5 +1,5 @@
-#!/bin/sh -e
-# Copyright 2009-2011 Wincent Colaiuta. All rights reserved.
+#!/bin/sh
+# Copyright 2009-2012 Wincent Colaiuta. All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -31,6 +31,9 @@ ENVIRONMENT=production
 REPO=elastic1.unixhosts.net:/pub/git/private/wincent.com.git
 BRANCH=master
 
+# misc vars:
+LOGFILE=log/deploy.log
+
 staging_environment_overrides() {
   if [ -z "$STAGING_SERVER" ]; then
     bail 'STAGING_SERVER environment variable not set'
@@ -40,12 +43,35 @@ staging_environment_overrides() {
 }
 
 bail() {
-  echo "  failed: $1"
+  p "  failed: $@"
   exit 1
 }
 
 warn() {
-  echo "  warning: $1"
+  p "  warning: $@"
+}
+
+p() {
+  echo "$@"
+  log "$@"
+}
+
+log() {
+  echo "$@" >> $LOGFILE
+}
+
+run() {
+  set +e
+  local REMOTE_USER=$1; shift
+  log "Running remote command: $@"
+  ssh -l $REMOTE_USER $SERVER "$@" 2>&1 >> $LOGFILE
+  local EXIT_STATUS=$?
+  if [ $EXIT_STATUS -ne 0 ]; then
+    p "Failed remote command: $@"
+    p "Exit status: $EXIT_STATUS"
+    exit $EXIT_STATUS
+  fi
+  set -e
 }
 
 usage() {
@@ -210,30 +236,31 @@ test -n "$DO_UNLOCK" \
   -o -n "$DO_UPLOAD" \
   -o -n "$DO_LOCKDOWN" || usage
 
-trap 'test -n "$SUCCESS" || echo "  error: aborted"' EXIT
+trap 'test -n "$SUCCESS" || p "  error: aborted; see $LOGFILE for details"' EXIT
 
-echo "Environment for this session: $ENVIRONMENT"
+p "Starting deploy at: $(date)"
+p "Environment for this session: $ENVIRONMENT"
 
 if [ -n "$DO_UNLOCK" ]; then
-   echo "Processing command: unlock"
-   ssh root@$SERVER chsh -s /bin/sh rails > /dev/null
+   p "Processing command: unlock"
+   run root chsh -s /bin/sh rails
 fi
 
 # useful because remote system sometimes won't notice "unlock" immediately
 if [ -n "$DO_WAIT" ]; then
-  echo "Processing command: wait"
+  p "Processing command: wait"
   sleep 15
 fi
 
 if [ -n "$DO_CHECK" ]; then
-  echo "Processing command: check"
+  p "Processing command: check"
   TMPDIR=$(mktemp -q -d /private/tmp/deploy.XXXXXX) || bail "could not create temporary directory"
   if [ -z "$REF" ]; then
     LOCAL_REF=$BRANCH
   else
     LOCAL_REF=$REF
   fi
-  echo "  checking: generated static HTML files up-to-date"
+  p "  checking: generated static HTML files up-to-date"
   for HAML in $(ls app/views/public/*.html.haml); do
     git show $LOCAL_REF:$HAML > $TMPDIR/src.html.haml
     STATIC=${HAML%.haml}        # trim extension
@@ -242,38 +269,38 @@ if [ -n "$DO_CHECK" ]; then
     script/static $TMPDIR/src.html.haml $TMPDIR/out.html
     diff -q $TMPDIR/out.html $TMPDIR/static.html > /dev/null || bail "static version of $HAML not up-to-date in $LOCAL_REF"
   done
-  echo "  checking: directories exist and are writable"
-  ssh rails@$SERVER "sh -c '(test -d $DEPLOY          || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
-                            (test -d $DEPLOY/shared   || (echo \"  failed -d: $DEPLOY/shared\" && exit 1)) && \
-                            (test -d $DEPLOY/releases || (echo \"  failed -d: $DEPLOY/releases\" && exit 1)) && \
-                            (test -w $DEPLOY          || (echo \"  failed -w: $DEPLOY\" && exit 1)) && \
-                            (test -w $DEPLOY/releases || (echo \"  failed -w: $DEPLOY/releases\" && exit 1))'"
-  echo "  checking: executables exist"
-  ssh rails@$SERVER "sh -l -c 'which gem git > /dev/null'"
-  echo "  checking: gem versions"
-  ssh rails@$SERVER "sh -c 'gem specification --version \"~> 1.0.10\" bundler > /dev/null'"
-  echo "  checking: local branch vs remote branch"
+  p "  checking: directories exist and are writable"
+  run rails test -d $DEPLOY
+  run rails test -d $DEPLOY/shared
+  run rails test -d $DEPLOY/releases
+  run rails test -w $DEPLOY
+  run rails test -w $DEPLOY/releases
+  p "  checking: executables exist"
+  run rails which gem git
+  p "  checking: gem versions"
+  run rails gem specification --version 1.1.4 bundler
+  p "  checking: local branch vs remote branch"
   git diff --exit-code --quiet $BRANCH origin/$BRANCH || \
     warn "local $BRANCH differs from remote origin/$BRANCH -- did you remember to 'git push'?"
-  echo "  checking: currently checked out branch"
+  p "  checking: currently checked out branch"
   CURRENT_BRANCH=$(git symbolic-ref HEAD 2> /dev/null)
   CURRENT_BRANCH=${CURRENT_BRANCH#refs/heads/}
   test "$CURRENT_BRANCH" = "$BRANCH" || \
     warn "currently on branch $CURRENT_BRANCH (expected $BRANCH) -- sure you're working on the right branch?"
-  echo "  checking: schema is up-to-date"
+  p "  checking: schema is up-to-date"
   env SCHEMA=$TMPDIR/schema.HEAD.rb bin/rake --silent db:schema:dump
   git show $LOCAL_REF:db/schema.rb > $TMPDIR/schema.REF.rb
   diff -q -b $TMPDIR/schema.REF.rb $TMPDIR/schema.HEAD.rb > /dev/null || \
     warn "current schema does not match $LOCAL_REF:db/schema.rb -- did you remember to run rake 'db:schema:dump' and check in the result?"
-  echo "  checking: worktree is clean"
+  p "  checking: worktree is clean"
   git diff --quiet || \
     warn "worktree has uncommitted changes -- did the specs really pass against what you're going to deploy?"
 fi
 
 if [ -n "$DO_DEPLOY" ]; then
-  echo "Processing command: deploy"
+  p "Processing command: deploy"
   TIMESTAMP=$(date '+%Y%m%d%H%M%S')
-  echo "  timestamp: $TIMESTAMP"
+  p "  timestamp: $TIMESTAMP"
   SHARED=$DEPLOY/shared
   CHECKOUT=$DEPLOY/releases/$TIMESTAMP
   if [ -z "$REF" ]; then
@@ -281,63 +308,60 @@ if [ -n "$DO_DEPLOY" ]; then
   else
     REMOTE_REF=$REF
   fi
-  ssh rails@$SERVER "sh -l -c '(test ! -e $TIMESTAMP || (echo \"  failed: $CHECKOUT already exists\" && exit 1)) && \
-                                git clone --quiet $REPO $CHECKOUT && \
-                                cd $CHECKOUT && \
-                                git checkout --quiet -b deploy $REMOTE_REF > /dev/null && \
-                                git submodule --quiet init && \
-                                git submodule --quiet update > /dev/null && \
-                                (git rev-parse HEAD > $CHECKOUT/REVISION) && \
-                                rm -rf $CHECKOUT/log \
-                                       $CHECKOUT/public/assets \
-                                       $CHECKOUT/public/system \
-                                       $CHECKOUT/tmp/pids && \
-                                ln -s $SHARED/log             $CHECKOUT/log && \
-                                ln -s $SHARED/assets          $CHECKOUT/public/assets && \
-                                ln -s $SHARED/system          $CHECKOUT/public/system && \
-                                ln -s $SHARED/pids            $CHECKOUT/tmp/pids && \
-                                ln -s $SHARED/database.yml    $CHECKOUT/config/database.yml && \
-                                ln -s $SHARED/app_config.yml  $CHECKOUT/config/app_config.yml && \
-                                rm -f $DEPLOY/latest && \
-                                ln -s $CHECKOUT $DEPLOY/latest && \
-                                cd $CHECKOUT && \
-                                bundle install --quiet --deployment --local --binstubs \
-                                       --path /data/rails/deploy/shared/bundle \
-                                       --without test && \
-                                bin/rake --silent assets:precompile &> /dev/null'"
+  run rails test ! -e $CHECKOUT
+  run rails git clone --quiet --recursive $REPO $CHECKOUT
+  run rails "cd $CHECKOUT && git checkout --quiet -b deploy $REMOTE_REF"
+  run rails "cd $CHECKOUT && git submodule --quiet update --init"
+  run rails "cd $CHECKOUT && (git rev-parse HEAD > $CHECKOUT/REVISION)"
+  run rails rm -rf $CHECKOUT/log \
+                   $CHECKOUT/public/assets \
+                   $CHECKOUT/public/system \
+                   $CHECKOUT/tmp/pids
+  run rails ln -s $SHARED/log             $CHECKOUT/log
+  run rails ln -s $SHARED/assets          $CHECKOUT/public/assets
+  run rails ln -s $SHARED/system          $CHECKOUT/public/system
+  run rails ln -s $SHARED/pids            $CHECKOUT/tmp/pids
+  run rails ln -s $SHARED/database.yml    $CHECKOUT/config/database.yml
+  run rails ln -s $SHARED/app_config.yml  $CHECKOUT/config/app_config.yml
+  run rails rm -f $DEPLOY/latest
+  run rails ln -s $CHECKOUT $DEPLOY/latest
+  run rails "cd $CHECKOUT && \
+             bundle install --quiet --deployment --local --binstubs \
+                            --path /data/rails/deploy/shared/bundle \
+                            --without test"
+  run rails "cd $CHECKOUT && bin/rake --silent assets:precompile"
 fi
 
 if [ -n "$DO_DISABLE" ]; then
-  echo "Processing command: disable"
-  ssh rails@$SERVER cp $DEPLOY/current/public/maintenance.html \
-                       $DEPLOY/shared/system/maintenance.html
+  p "Processing command: disable"
+  run rails cp $DEPLOY/current/public/maintenance.html \
+               $DEPLOY/shared/system/maintenance.html
 fi
 
 if [ -n "$DO_MIGRATE" ]; then
   # we migrate all databases, not just production, as a sanity check
-  echo "Processing command: migrate"
-  ssh rails@$SERVER "sh -c 'cd $DEPLOY/latest && \
-                            bin/rake --silent RAILS_ENV=test         db:migrate && \
-                            bin/rake --silent RAILS_ENV=development  db:migrate && \
-                            bin/rake --silent RAILS_ENV=migrations   db:migrate && \
-                            bin/rake --silent RAILS_ENV=production   db:schema:dump && \
-                            (git diff --quiet --ignore-space-change -- db/schema.rb || \
-                            (echo \"  failed: db/schema.rb out of sync with checked-in version\" && exit 1))'"
+  p "Processing command: migrate"
+  run rails "cd $DEPLOY/latest && bin/rake --silent RAILS_ENV=test db:migrate"
+  run rails "cd $DEPLOY/latest && bin/rake --silent RAILS_ENV=development db:migrate"
+  run rails "cd $DEPLOY/latest && bin/rake --silent RAILS_ENV=migrations db:migrate"
+  run rails "cd $DEPLOY/latest && bin/rake --silent RAILS_ENV=production db:schema:dump"
+  run rails "cd $DEPLOY/latest && \
+             (git diff --quiet --ignore-space-change -- db/schema.rb || \
+             (echo \"  failed: db/schema.rb out of sync with checked-in version\"; exit 1))"
 fi
 
 if [ -n "$DO_SWITCH" ]; then
-  echo "Processing command: switch"
+  p "Processing command: switch"
   LATEST=$DEPLOY/latest
   CURRENT=$DEPLOY/current
-  ssh rails@$SERVER "sh -c '(test -d $LATEST || (echo \"  failed: no deployment found at $LATEST\" && exit 1)) && \
-                             rm -f $CURRENT && \
-                             ln -s \$(readlink $LATEST) $CURRENT'"
+  run rails test -d $LATEST
+  run rails "rm -f $CURRENT && ln -s \$(readlink $LATEST) $CURRENT"
   REVISION=$(ssh rails@$SERVER cat $LATEST/REVISION)
   if [ ! $(git describe --exact-match $REVISION 2> /dev/null) ]; then
     TAG=$(git describe $(git rev-list --tags --max-count=1) | awk -F . '{ printf "%d.%d", $1, $2 + 1}')
     if [ $ENVIRONMENT = staging ]; then
       warn "deployed version $REVISION is not yet tagged; would tag now as $TAG"
-      echo "  skipping: no tagging is performed in the staging environment"
+      p "  skipping: no tagging is performed in the staging environment"
     else
       warn "deployed version $REVISION is not yet tagged; tagging now as $TAG"
       git tag -s -m "Deployed $(LANG=en_GB.UTF-8; date '+%d %B %Y')." $TAG $REVISION
@@ -346,27 +370,27 @@ if [ -n "$DO_SWITCH" ]; then
 fi
 
 if [ -n "$DO_STOP" ]; then
-  echo "Processing command: stop"
-  ssh root@$SERVER monit stop unicorn
+  p "Processing command: stop"
+  run root monit stop unicorn
 fi
 
 if [ -n "$DO_RESTART" ]; then
-  echo "Processing command: restart"
-  ssh root@$SERVER monit restart unicorn
+  p "Processing command: restart"
+  run root monit restart unicorn
 fi
 
 if [ -n "$DO_START" ]; then
-  echo "Processing command: start"
-  ssh root@$SERVER monit start unicorn
+  p "Processing command: start"
+  run root monit start unicorn
 fi
 
 if [ -n "$DO_ENABLE" ]; then
-  echo "Processing command: enable"
-  ssh rails@$SERVER rm -f $DEPLOY/shared/system/maintenance.html
+  p "Processing command: enable"
+  run rails rm -f $DEPLOY/shared/system/maintenance.html
 fi
 
 if [ -n "$DO_SUMMARY" ]; then
-  echo "Processing command: summary"
+  p "Processing command: summary"
   REVISION=$(ssh rails@$SERVER cat $DEPLOY/latest/REVISION)
   if [ $(git describe --exact-match $REVISION 2> /dev/null) ]; then
     # common case: latest deployed revision is tagged
@@ -376,17 +400,17 @@ if [ -n "$DO_SUMMARY" ]; then
     LAST_TAG=$(git describe $(git rev-list --tags --max-count=1))
   fi
   CURRENT_TAG=$(git describe $REVISION)
-  echo "----- start: changes from $LAST_TAG..$CURRENT_TAG -----"
+  p "----- start: changes from $LAST_TAG..$CURRENT_TAG -----"
   PAGER=cat git log --oneline --no-color --no-decorate --reverse $LAST_TAG..$REVISION
-  echo "-----   end: changes from $LAST_TAG..$CURRENT_TAG -----"
+  p "-----   end: changes from $LAST_TAG..$CURRENT_TAG -----"
 fi
 
 if [ -n "$DO_UPLOAD" ]; then
-  echo "Processing command: upload"
+  p "Processing command: upload"
   test -n "$FILES" || warn "nothing specified in FILES environment variable"
   (IFS=","
   for FILE in $FILES; do
-    echo "  file: $FILE"
+    p "  file: $FILE"
     if [[ "$FILE" =~ ' ' ]]; then
       warn "\"$FILE\" contains a space; skipping"
     else
@@ -396,8 +420,9 @@ if [ -n "$DO_UPLOAD" ]; then
 fi
 
 if [ -n "$DO_LOCKDOWN" ]; then
-  echo "Processing command: lockdown"
-  ssh root@$SERVER chsh -s /sbin/nologin rails > /dev/null
+  p "Processing command: lockdown"
+  run root chsh -s /sbin/nologin rails
 fi
 
+p "Finished deploy at: $(date)"
 SUCCESS=true
