script/deploy: fix incorrect paths in "switch" subcommand
Note also that we weren't bailing even though the paths were incorrect.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -229,9 +229,9 @@ fi
 
 if [ -n "$DO_SWITCH" ]; then
   echo "Processing command: switch"
-  LATEST=$DEPLOY/releases/latest
-  CURRENT=$DEPLOY/releases/current
-  ssh $SERVER "sh -c '(test -d $LATEST || echo \"  failed: no deployment found at $LATEST\") && \
+  LATEST=$DEPLOY/latest
+  CURRENT=$DEPLOY/current
+  ssh $SERVER "sh -c '(test -d $LATEST || (echo \"  failed: no deployment found at $LATEST\" && exit 1)) && \
                       rm -f $CURRENT && \
                       ln -s $LATEST $CURRENT'"
 fi
