script/deploy: add "bail()" function and use it
As mentioned in commit 46b52cb, there were places in the script where an
error wasn't actually aborting the run because of our use of subshells.
Even when running with the "-e" switch, constructs like this won't work:

  try_something || (echo "failed!" && exit 1)

The problem is that the "exit 1" only exits the subshell, and even
though the exit status does "bubble up" to the parent shell, it is not
enough to abort the parent script because "-e" only affects "simple
commands", not subshells.

In other words, this will abort:

  #!/bin/sh -e
  ls non-existent-directory
  echo "never shown"

But this will not:

  #!/bin/sh -e
  (exit 1)
  echo "this is shown"

The solution is to not use subshells for grouping the two statements of
the echo-then-exit pattern; rather we must use a function like the
"bail" function added in this commit.

Note that our other uses of subshells _do_ work because they _are_
considered "simple commands". For example:

  ssh $SERVER "sh -c '(test -d $A || (echo \"failed\" && exit 1)) &&
                      (test -d $B || (echo \"failed\" && exit 1)) &&
                      (test -d $C || (echo \"failed\" && exit 1))'"

Here because the commands are chained together rather than sequential,
every single one must pass with zero exit status in order for the "sh"
command to return a zero exit status, and in turn "ssh". If any of the
three tests fail, the exit status will be 1, and as "ssh" is a "simple
command", the shell script will abort.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -21,6 +21,11 @@ staging_environment_overrides() {
   ENVIRONMENT=staging
 }
 
+bail() {
+  echo $1
+  exit 1
+}
+
 usage() {
   echo "Usage:"
   echo "  $0 [options] command..."
@@ -206,9 +211,9 @@ if [ -n "$DO_CHECK" ]; then
   echo "  checking: JavaScript is correctly minimized"
   #COMPRESSOR=/usr/local/bin/closure/compiler.jar
   COMPRESSOR=/usr/local/bin/yuicompressor.jar
-  test -f $COMPRESSOR || (echo "  failed: compressor not found at $COMPRESSOR" && exit 1)
-  #test -r $COMPRESSOR || (echo "  failed: compressor not readable at $COMPRESSOR" && exit 1)
-  TMPDIR=$(mktemp -q -d /private/tmp/deploy.XXXXXX) || (echo "  failed: could not create temporary directory" && exit 1)
+  test -f $COMPRESSOR || bail "  failed: compressor not found at $COMPRESSOR"
+  #test -r $COMPRESSOR || bail "  failed: compressor not readable at $COMPRESSOR"
+  TMPDIR=$(mktemp -q -d /private/tmp/deploy.XXXXXX) || bail "  failed: could not create temporary directory"
   if [ -z "$REF" ]; then
     LOCAL_REF=$BRANCH
   else
@@ -219,7 +224,7 @@ if [ -n "$DO_CHECK" ]; then
     git show $LOCAL_REF:${JS/.max.js/.min.js} > $TMPDIR/min.js
     java -jar $COMPRESSOR -o $TMPDIR/out.js $TMPDIR/max.js
     #java -jar $COMPRESSOR --js=$TMPDIR/max.js --js_output_file=$TMPDIR/out.js
-    diff -q $TMPDIR/min.js $TMPDIR/out.js > /dev/null || (echo "  failed: $JS is not minimized in $LOCAL_REF" && exit 1)
+    diff -q $TMPDIR/min.js $TMPDIR/out.js > /dev/null || bail "  failed: $JS is not minimized in $LOCAL_REF"
   done
   echo "  checking: directories exist and are writable"
   ssh $SERVER "sh -c '(test -d $DEPLOY          || (echo \"  failed -d: $DEPLOY\" && exit 1)) && \
