script/deploy: warn of early exits
Seeing as the script is running with "-e" set make sure that early exits
don't go unnoticed. If we don't make it to the end of the script we want
the user to see at the very least this "error: aborted" message.

Signed-off-by: Wincent Colaiuta <win@wincent.com>

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -32,6 +32,12 @@ usage() {
   echo "   --rev=REF    deploy specified tag/branch/commit"
 }
 
+#
+# main
+#
+
+trap 'test -n "$SUCCESS" || echo "error: aborted"' EXIT
+
 # process arguments
 while test $# != 0; do
   case "$1" in
@@ -63,3 +69,5 @@ fi
 if [ -n "$LOCKDOWN" ]; then
   echo "Processing command: lockdown"
 fi
+
+SUCCESS=true
